# Generated by Django 4.0.3 on 2022-11-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='userid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='contractPoint',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='number',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='panel',
            name='period',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='point',
            field=models.CharField(default='', max_length=10),
        ),
    ]
