# Generated by Django 4.0.3 on 2022-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0002_panel_userid_alter_panel_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberId', models.CharField(default='', max_length=10)),
                ('numberDesc', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
