# Generated by Django 4.0.3 on 2022-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0003_numbermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorId', models.CharField(default='', max_length=10)),
                ('colorDesc', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
