# Generated by Django 4.0.3 on 2022-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0004_colormaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormaster',
            name='colorCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
