# Generated by Django 4.0.3 on 2022-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0005_colormaster_colorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.CharField(default='', max_length=10)),
                ('recordNumber', models.CharField(default='', max_length=10)),
                ('openTime', models.CharField(default='', max_length=10)),
                ('periodNumber', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('colorId', models.CharField(default='', max_length=10)),
                ('numberId', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
