# Generated by Django 4.0.3 on 2023-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0006_recorddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodId', models.CharField(default='', max_length=10000)),
                ('perriodDate', models.CharField(default='', max_length=10000)),
                ('perriodCode', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
