# Generated by Django 4.0.3 on 2023-02-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0007_periodmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodmaster',
            old_name='perriodCode',
            new_name='periodCode',
        ),
        migrations.RenameField(
            model_name='periodmaster',
            old_name='perriodDate',
            new_name='periodDate',
        ),
    ]
